name: Delete Preview Deployment

on: deployment_status

jobs:
  delete_production:
    if: ${{ github.event.deployment_status.environment == 'production' && github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run script
        run: node --experimental-fetch ./scripts/delete_production.mjs

  delete_preview:
    if: ${{ github.event.deployment_status.environment == 'preview' && github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: test
        run: echo $VERCEL_ACCESS_TOKEN
        env:
          VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}

      - name: Run script
        run: node --experimental-fetch ./scripts/delete_preview.mjs
        env:
          VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
