name: Delete Preview Deployment

on:
  pull_request:
    types: ["closed"]
    branches:
      - main
      - develop
  push:
    branches:
      - main

env:
  VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}

jobs:
  delete_production:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run script
        run: node --experimental-fetch ./scripts/delete_production.mjs

  delete_preview:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run script
        run: node --experimental-fetch ./scripts/delete_preview.mjs
