name: Release Tag
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  build:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'release/')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 버전 정보 추출
        run: echo "version=$(echo '${{ github.event.pull_request.base.ref }}' | egrep -o 'v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_OUTPUT
        id: extract_version_name

      - name: Release 생성
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.extract_version_name.outputs.version }}
